sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
env:
  matrix:
    - BUILD_TOOL="maven"
    - BUILD_TOOL="gradle"
script: ./travis.sh
